"""
Validation Node.

Evaluates the quality of the draft response before routing.
Checks for length, missing information, intent confidence, and policy alignment.
"""

from __future__ import annotations

import logging
import time

from app.core.schemas import (
    DraftResult,
    IntentResult,
    PolicyResult,
    ValidationResult,
)
from app.core.settings import settings

logger = logging.getLogger(__name__)


def _check_response_length(draft: DraftResult) -> tuple[bool, str]:
    """Ensure the response is not too short."""
    if len(draft.draft_response.strip()) < settings.min_response_length:
        return False, f"Response too short ({len(draft.draft_response)} chars < {settings.min_response_length})"
    return True, ""


def _check_missing_information(draft: DraftResult) -> tuple[bool, str]:
    """Flag if critical information is missing."""
    if len(draft.missing_information) > 3:
        return False, f"Too many missing information fields ({len(draft.missing_information)})"
    return True, ""


def _check_intent_confidence(intent_result: IntentResult) -> tuple[bool, str]:
    """Flag low-confidence intent detection."""
    if intent_result.confidence < settings.min_intent_confidence:
        return False, f"Low intent confidence ({intent_result.confidence:.0%} < {settings.min_intent_confidence:.0%})"
    return True, ""


def _check_policy_match(intent_result: IntentResult, policy_result: PolicyResult) -> tuple[bool, str]:
    """Ensure the retrieved policy matches the detected intent."""
    if not policy_result.policy_found:
        return False, "No specific policy found for detected intent"
    if policy_result.intent != intent_result.intent:
        return False, f"Policy intent mismatch: policy={policy_result.intent} vs detected={intent_result.intent}"
    return True, ""


def _check_fallback_model(draft: DraftResult) -> tuple[bool, str]:
    """Warn if the draft was generated by the fallback (non-LLM) path."""
    if draft.model_used == "fallback":
        return False, "Response was generated by fallback (LLM unavailable)"
    return True, ""


async def run_validation_node(
    intent_result: IntentResult,
    policy_result: PolicyResult,
    draft_result: DraftResult,
) -> ValidationResult:
    """Validate the draft response against quality criteria.

    Args:
        intent_result: Output from Intent Node.
        policy_result: Output from Policy Node.
        draft_result: Output from Draft Node.

    Returns:
        :class:`ValidationResult` with score, issues list, and validity flag.
    """
    start = time.perf_counter()

    checks: list[tuple[bool, str]] = [
        _check_response_length(draft_result),
        _check_missing_information(draft_result),
        _check_intent_confidence(intent_result),
        _check_policy_match(intent_result, policy_result),
        _check_fallback_model(draft_result),
    ]

    passed = sum(1 for ok, _ in checks if ok)
    issues = [msg for ok, msg in checks if not ok]
    score = round(passed / len(checks), 2)
    is_valid = score >= settings.min_validation_score and not issues

    latency = (time.perf_counter() - start) * 1000
    logger.info(
        "ValidationNode: score=%.2f issues=%d valid=%s latency=%.1fms",
        score,
        len(issues),
        is_valid,
        latency,
    )

    return ValidationResult(
        is_valid=is_valid,
        validation_score=score,
        validation_issues=issues,
        latency_ms=round(latency, 2),
    )
